### PR TITLE
#1 index file generation

### LINKED ISSUE #1: Add index file
When initializing ADR, using the tool, create an index file (name suggestion `000 - Index.md`).

This file will contain a list of all ADR documents, created by the tool.
The list will show the number and title of the document. 

If a document has been superseded, the entry will be striked through and reference the superseded document. Example:
> ~~001 - Sample~~ (superseded by: `003 - Superseded sample`)

### PR DESCRIPTION
**Pull request by FarshanAhamed**
Index file generation on creating a new ADR.

```
# Index

| Number | Title | Superseded by |
| ------ | ----- | ------------- |
| 1 | [Record Architecture Decisions](./0001-record-architecture-decisions.md)| |
| 2 | [Use ISO 8601 Date Format](./0002-use-iso-8601-date-format.md)| |
| 3 | [Use docs/adr as folder](./0003-use-docs-adr-as-folder.md)| |
| 4 | [Record Architecture Decisions](./0004-record-architecture-decisions.md)| |

```

### CODE REVIEW

**Comment by FarshanAhamed** [comment]
`Superseded By` column is left blank for now. Once #2 is completed, it can be implemented

**Comment by Jandev** [comment]
Looks good on first impression. Not able to do a full review at the moment, hope to get back to it tomorrow.

**Comment by FarshanAhamed** [comment]
Sure. As you mentioned in #2, I have just added the changes in index-file-generation when a superseded record appears in the index file. After implementing the full functionality of superseded documents, we can identify the superseded record from the document body using a regular expression.

**Comment by Jandev** [comment]
I've tested the generation in Visual Studio with a debug argument and it appears to work.
```markdown
# Index

| Number | Title | Superseded by |
| ------ | ----- | ------------- |
| 1 | [Record Architecture Decisions](./0001-record-architecture-decisions.md)| |
| 2 | [Helloworld](./0002-helloworld.md)| |
| 3 | [Helloworld3](./0003-helloworld3.md)| |
| 4 | [Helloworld4](./0004-helloworld4.md)| |
| 5 | [Helloworld4](./0005-helloworld4.md)| |
| 6 | [Helloworld4](./0006-helloworld4.md)| |

```

However, when running it from the command-line with `adr-cli generate`, nothing gets created. Can you confirm this works on your end? If so, it's probably some setting on my machine.

**Comment by FarshanAhamed** [comment]
the command `init` will generate the index file as of now. 

Since there is nothing happening on `generate` command previously, 

`  app.Command("generate", (command) =>
            {
                command.Description = "";
                command.OnExecute(() =>
                {
                    return 0;
                });
            });`

I have only triggered the index file generation on `init` command . So `adr-cli init` will work I guess.

**Comment by Jandev** [comment]
Yes, I figured the same indeed. However, when running the command from the CLI it fails to create the index file, where it does create the initial file.
Also, new files do get created.

image

Running the code from VS does trigger the creation of the index file.

**Comment by FarshanAhamed** [comment]
it is working on my end after I have cleared the `bin` and `obj` folders. Verify the path you have set in the `adr.config.json` is correct

image

**Pull request merged**
